apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chap.fullname" . }}
  labels:
    {{- include "chap.labels" . | nindent 4 }}
data:
  {{- if .Values.postgresql.managed.enabled }}
  POSTGRES_HOST: {{ include "chap.fullname" . }}-postgres-rw
  POSTGRES_DB: {{ .Values.postgresql.managed.database | quote }}
  {{- else }}
  POSTGRES_HOST: {{ .Values.postgresql.external.host | quote }}
  POSTGRES_DB: {{ .Values.postgresql.external.database | quote }}
  {{- end }}
  POSTGRES_PORT: {{ .Values.postgresql.external.port | quote }}
  REDIS_HOST: {{ .Values.valkeyConnection.host | quote }}
  REDIS_PORT: {{ .Values.valkeyConnection.port | quote }}
